export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";


export const ADD_TASKS_REQUEST = "ADD_TASKS_REQUEST";
export const ADD_TASKS_SUCCESS = "ADD_TASKS_SUCCESS";
export const ADD_TASKS_FAILED = "ADD_TASKS_FAILED";


export const DELETE_TASKS_REQUEST = "DELETE_TASKS_REQUEST";
export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS";
export const DELETE_TASKS_FAILED = "DELETE_TASKS_FAILED";


export const UPDATE_TASKS_REQUEST = "UPDATE_TASKS_REQUEST";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILED = "UPDATE_TASKS_FAILED";


export const GET_SINGLE_TASK_REQUEST = "GET_SINGLE_TASK_REQUEST";
export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";
export const GET_SINGLE_TASK_FAILED = "GET_SINGLE_TASK_FAILED";


export const UPDATE_TASKS_STATUS_REQUEST = "UPDATE_TASKS_STATUS_REQUEST";
export const UPDATE_TASKS_STATUS_SUCCESS = "UPDATE_TASKS_STATUS_SUCCESS";
export const UPDATE_TASKS_STATUS_FAILED = "UPDATE_TASKS_STATUS_FAILED";


export default {
    GET_TASKS_REQUEST,
    GET_TASKS_SUCCESS,
    GET_TASKS_FAILED,

    ADD_TASKS_REQUEST,
    ADD_TASKS_SUCCESS,
    ADD_TASKS_FAILED,

    GET_SINGLE_TASK_REQUEST,
    GET_SINGLE_TASK_SUCCESS,
    GET_SINGLE_TASK_FAILED,

    DELETE_TASKS_REQUEST,
    DELETE_TASKS_SUCCESS,
    DELETE_TASKS_FAILED,


    UPDATE_TASKS_REQUEST,
    UPDATE_TASKS_SUCCESS,
    UPDATE_TASKS_FAILED,


    UPDATE_TASKS_STATUS_REQUEST,
    UPDATE_TASKS_STATUS_SUCCESS,
    UPDATE_TASKS_STATUS_FAILED
}
