const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

const CHECK_USER_REQUEST = "CHECK_USER_REQUEST";
const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
const CHECK_USER_FAILED = "CHECK_USER_FAILED";



export default {
    LOGIN_USER_REQUEST ,
    LOGIN_USER_SUCCESS,
    LOGIN_USER_FAILED,

    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAILED,

    CHECK_USER_REQUEST,
    CHECK_USER_SUCCESS,
    CHECK_USER_FAILED,
}
